/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_antell_cloudhands_api_packet_security_clamav_ClamAVScan */

#ifndef _Included_com_antell_cloudhands_api_packet_security_clamav_ClamAVScan
#define _Included_com_antell_cloudhands_api_packet_security_clamav_ClamAVScan
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_antell_cloudhands_api_packet_security_clamav_ClamAVScan
 * Method:    init
 * Signature: (Ljava/lang/String;I)I
 */
JNIEXPORT jint JNICALL Java_com_antell_cloudhands_api_packet_security_clamav_ClamAVScan_init
  (JNIEnv *, jobject, jstring, jint);

/*
 * Class:     com_antell_cloudhands_api_packet_security_clamav_ClamAVScan
 * Method:    scanFile
 * Signature: (Ljava/lang/String;I)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_antell_cloudhands_api_packet_security_clamav_ClamAVScan_scanFile
  (JNIEnv *, jobject, jstring, jint);

#ifdef __cplusplus
}
#endif
#endif
