/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_antell_cloudhands_api_packet_PacketRecordReader */

#ifndef _Included_com_antell_cloudhands_api_packet_PacketRecordReader
#define _Included_com_antell_cloudhands_api_packet_PacketRecordReader
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_antell_cloudhands_api_packet_PacketRecordReader
 * Method:    openMMap
 * Signature: (ILjava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_com_antell_cloudhands_api_packet_PacketRecordReader_openMMap
  (JNIEnv *, jobject, jint, jstring);

/*
 * Class:     com_antell_cloudhands_api_packet_PacketRecordReader
 * Method:    openSHM
 * Signature: (ILjava/lang/String;I)I
 */
JNIEXPORT jint JNICALL Java_com_antell_cloudhands_api_packet_PacketRecordReader_openSHM
  (JNIEnv *, jobject, jint, jstring, jint);

/*
 * Class:     com_antell_cloudhands_api_packet_PacketRecordReader
 * Method:    read
 * Signature: (ILcom/antell/cloudhands/api/packet/PacketRecord;)I
 */
JNIEXPORT jint JNICALL Java_com_antell_cloudhands_api_packet_PacketRecordReader_read
  (JNIEnv *, jobject, jint, jobject);

/*
 * Class:     com_antell_cloudhands_api_packet_PacketRecordReader
 * Method:    close
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_com_antell_cloudhands_api_packet_PacketRecordReader_close
  (JNIEnv *, jobject, jint);

#ifdef __cplusplus
}
#endif
#endif
