/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_antell_cloudhands_api_smon_SessionMonitorCmd */

#ifndef _Included_com_antell_cloudhands_api_smon_SessionMonitorCmd
#define _Included_com_antell_cloudhands_api_smon_SessionMonitorCmd
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_antell_cloudhands_api_smon_SessionMonitorCmd
 * Method:    open
 * Signature: (Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_com_antell_cloudhands_api_smon_SessionMonitorCmd_open
  (JNIEnv *, jobject, jstring);

/*
 * Class:     com_antell_cloudhands_api_smon_SessionMonitorCmd
 * Method:    close
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_antell_cloudhands_api_smon_SessionMonitorCmd_close
  (JNIEnv *, jobject);

/*
 * Class:     com_antell_cloudhands_api_smon_SessionMonitorCmd
 * Method:    add
 * Signature: (JJ)J
 */
JNIEXPORT jlong JNICALL Java_com_antell_cloudhands_api_smon_SessionMonitorCmd_add__JJ
  (JNIEnv *, jobject, jlong, jlong);

/*
 * Class:     com_antell_cloudhands_api_smon_SessionMonitorCmd
 * Method:    add
 * Signature: (IJ)J
 */
JNIEXPORT jlong JNICALL Java_com_antell_cloudhands_api_smon_SessionMonitorCmd_add__IJ
  (JNIEnv *, jobject, jint, jlong);

/*
 * Class:     com_antell_cloudhands_api_smon_SessionMonitorCmd
 * Method:    add
 * Signature: (JIJ)J
 */
JNIEXPORT jlong JNICALL Java_com_antell_cloudhands_api_smon_SessionMonitorCmd_add__JIJ
  (JNIEnv *, jobject, jlong, jint, jlong);

/*
 * Class:     com_antell_cloudhands_api_smon_SessionMonitorCmd
 * Method:    add
 * Signature: (JIJIJ)J
 */
JNIEXPORT jlong JNICALL Java_com_antell_cloudhands_api_smon_SessionMonitorCmd_add__JIJIJ
  (JNIEnv *, jobject, jlong, jint, jlong, jint, jlong);

/*
 * Class:     com_antell_cloudhands_api_smon_SessionMonitorCmd
 * Method:    find
 * Signature: (Lcom/antell/cloudhands/api/smon/SessionMonitorItem;J)I
 */
JNIEXPORT jint JNICALL Java_com_antell_cloudhands_api_smon_SessionMonitorCmd_find__Lcom_antell_cloudhands_api_smon_SessionMonitorItem_2J
  (JNIEnv *, jobject, jobject, jlong);

/*
 * Class:     com_antell_cloudhands_api_smon_SessionMonitorCmd
 * Method:    find
 * Signature: (Lcom/antell/cloudhands/api/smon/SessionMonitorItem;JIJI)I
 */
JNIEXPORT jint JNICALL Java_com_antell_cloudhands_api_smon_SessionMonitorCmd_find__Lcom_antell_cloudhands_api_smon_SessionMonitorItem_2JIJI
  (JNIEnv *, jobject, jobject, jlong, jint, jlong, jint);

/*
 * Class:     com_antell_cloudhands_api_smon_SessionMonitorCmd
 * Method:    delete
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_com_antell_cloudhands_api_smon_SessionMonitorCmd_delete
  (JNIEnv *, jobject, jlong);

/*
 * Class:     com_antell_cloudhands_api_smon_SessionMonitorCmd
 * Method:    stop
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_com_antell_cloudhands_api_smon_SessionMonitorCmd_stop
  (JNIEnv *, jobject, jlong);

/*
 * Class:     com_antell_cloudhands_api_smon_SessionMonitorCmd
 * Method:    restart
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_com_antell_cloudhands_api_smon_SessionMonitorCmd_restart
  (JNIEnv *, jobject, jlong);

#ifdef __cplusplus
}
#endif
#endif
