/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_antell_cloudhands_api_statistic_StatDataReader */

#ifndef _Included_com_antell_cloudhands_api_statistic_StatDataReader
#define _Included_com_antell_cloudhands_api_statistic_StatDataReader
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_antell_cloudhands_api_statistic_StatDataReader
 * Method:    open
 * Signature: (Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_com_antell_cloudhands_api_statistic_StatDataReader_open
  (JNIEnv *, jobject, jstring);

/*
 * Class:     com_antell_cloudhands_api_statistic_StatDataReader
 * Method:    read
 * Signature: (Lcom/antell/cloudhands/api/statistic/StatDataInput;J)I
 */
JNIEXPORT jint JNICALL Java_com_antell_cloudhands_api_statistic_StatDataReader_read__Lcom_antell_cloudhands_api_statistic_StatDataInput_2J
  (JNIEnv *, jobject, jobject, jlong);

/*
 * Class:     com_antell_cloudhands_api_statistic_StatDataReader
 * Method:    read
 * Signature: (Lcom/antell/cloudhands/api/statistic/StatDataInput;JI)I
 */
JNIEXPORT jint JNICALL Java_com_antell_cloudhands_api_statistic_StatDataReader_read__Lcom_antell_cloudhands_api_statistic_StatDataInput_2JI
  (JNIEnv *, jobject, jobject, jlong, jint);

/*
 * Class:     com_antell_cloudhands_api_statistic_StatDataReader
 * Method:    close
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_antell_cloudhands_api_statistic_StatDataReader_close
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
