/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_antell_cloudhands_api_smon_SessionMonitorCmd */

#ifndef _Included_com_antell_cloudhands_api_smon_SessionMonitorCmd
#define _Included_com_antell_cloudhands_api_smon_SessionMonitorCmd
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_antell_cloudhands_api_smon_SessionMonitorCmd
 * Method:    open
 * Signature: (ILjava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_com_antell_cloudhands_api_smon_SessionMonitorCmd_open
  (JNIEnv *, jobject, jint, jstring);

/*
 * Class:     com_antell_cloudhands_api_smon_SessionMonitorCmd
 * Method:    close
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_com_antell_cloudhands_api_smon_SessionMonitorCmd_close
  (JNIEnv *, jobject, jint);

/*
 * Class:     com_antell_cloudhands_api_smon_SessionMonitorCmd
 * Method:    add
 * Signature: (IJJ)J
 */
JNIEXPORT jlong JNICALL Java_com_antell_cloudhands_api_smon_SessionMonitorCmd_add__IJJ
  (JNIEnv *, jobject, jint, jlong, jlong);

/*
 * Class:     com_antell_cloudhands_api_smon_SessionMonitorCmd
 * Method:    add
 * Signature: (IIJ)J
 */
JNIEXPORT jlong JNICALL Java_com_antell_cloudhands_api_smon_SessionMonitorCmd_add__IIJ
  (JNIEnv *, jobject, jint, jint, jlong);

/*
 * Class:     com_antell_cloudhands_api_smon_SessionMonitorCmd
 * Method:    add
 * Signature: (IJIJ)J
 */
JNIEXPORT jlong JNICALL Java_com_antell_cloudhands_api_smon_SessionMonitorCmd_add__IJIJ
  (JNIEnv *, jobject, jint, jlong, jint, jlong);

/*
 * Class:     com_antell_cloudhands_api_smon_SessionMonitorCmd
 * Method:    add
 * Signature: (IJIJIJ)J
 */
JNIEXPORT jlong JNICALL Java_com_antell_cloudhands_api_smon_SessionMonitorCmd_add__IJIJIJ
  (JNIEnv *, jobject, jint, jlong, jint, jlong, jint, jlong);

/*
 * Class:     com_antell_cloudhands_api_smon_SessionMonitorCmd
 * Method:    find
 * Signature: (ILcom/antell/cloudhands/api/smon/SessionMonitorItem;J)I
 */
JNIEXPORT jint JNICALL Java_com_antell_cloudhands_api_smon_SessionMonitorCmd_find__ILcom_antell_cloudhands_api_smon_SessionMonitorItem_2J
  (JNIEnv *, jobject, jint, jobject, jlong);

/*
 * Class:     com_antell_cloudhands_api_smon_SessionMonitorCmd
 * Method:    find
 * Signature: (ILcom/antell/cloudhands/api/smon/SessionMonitorItem;JIJI)I
 */
JNIEXPORT jint JNICALL Java_com_antell_cloudhands_api_smon_SessionMonitorCmd_find__ILcom_antell_cloudhands_api_smon_SessionMonitorItem_2JIJI
  (JNIEnv *, jobject, jint, jobject, jlong, jint, jlong, jint);

/*
 * Class:     com_antell_cloudhands_api_smon_SessionMonitorCmd
 * Method:    delete
 * Signature: (IJ)I
 */
JNIEXPORT jint JNICALL Java_com_antell_cloudhands_api_smon_SessionMonitorCmd_delete
  (JNIEnv *, jobject, jint, jlong);

/*
 * Class:     com_antell_cloudhands_api_smon_SessionMonitorCmd
 * Method:    stop
 * Signature: (IJ)V
 */
JNIEXPORT void JNICALL Java_com_antell_cloudhands_api_smon_SessionMonitorCmd_stop
  (JNIEnv *, jobject, jint, jlong);

/*
 * Class:     com_antell_cloudhands_api_smon_SessionMonitorCmd
 * Method:    restart
 * Signature: (IJ)V
 */
JNIEXPORT void JNICALL Java_com_antell_cloudhands_api_smon_SessionMonitorCmd_restart
  (JNIEnv *, jobject, jint, jlong);

/*
 * Class:     com_antell_cloudhands_api_smon_SessionMonitorCmd
 * Method:    get
 * Signature: (ILcom/antell/cloudhands/api/smon/SessionMonitorItem;I)I
 */
JNIEXPORT jint JNICALL Java_com_antell_cloudhands_api_smon_SessionMonitorCmd_get
  (JNIEnv *, jobject, jint, jobject, jint);

/*
 * Class:     com_antell_cloudhands_api_smon_SessionMonitorCmd
 * Method:    count
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_com_antell_cloudhands_api_smon_SessionMonitorCmd_count
  (JNIEnv *, jobject, jint);

#ifdef __cplusplus
}
#endif
#endif
