/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_antell_security_stream_analysis_jni_PacketReader */

#ifndef _Included_com_antell_security_stream_analysis_jni_PacketReader
#define _Included_com_antell_security_stream_analysis_jni_PacketReader
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_antell_security_stream_analysis_jni_PacketReader
 * Method:    open
 * Signature: (Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_com_antell_security_stream_analysis_jni_PacketReader_open
  (JNIEnv *, jobject, jstring);

/*
 * Class:     com_antell_security_stream_analysis_jni_PacketReader
 * Method:    read
 * Signature: (Lcom/antell/security/stream/analysis/jni/PacketEntry;)I
 */
JNIEXPORT jint JNICALL Java_com_antell_security_stream_analysis_jni_PacketReader_read
  (JNIEnv *, jobject, jobject);

/*
 * Class:     com_antell_security_stream_analysis_jni_PacketReader
 * Method:    close
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_antell_security_stream_analysis_jni_PacketReader_close
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
