package com.antell.cloudhands.api.packet.udp.dns;

/**
 * Recource Record Signature - An RRSIG provides the digital signature of an
 * RRset, so that the data can be authenticated by a DNSSEC-capable resolver.
 * The signature is generated by a key contained in a DNSKEY Record.
 *
 * @see RRset
 * @see KEYRecord
 */

public class RRSIGRecord extends SIGBase {


    public RRSIGRecord() {
    }

    @Override
    public Record getObject() {
        return new RRSIGRecord();
    }



}
