package com.antell.cloudhands.api.packet.udp.dns;


/**
 * Signature - A SIG provides the digital signature of an RRset, so that
 * the data can be authenticated by a DNSSEC-capable resolver.  The
 * signature is usually generated by a key contained in a KEYRecord
 *
 * @see RRset
 * @see KEYRecord
 */

public class SIGRecord extends SIGBase {


    public SIGRecord() {
    }

    @Override
    public Record getObject() {
        return new SIGRecord();
    }


}
